server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: backend
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/mma_scoring_dev?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "@RMAWLrkawl8500"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
